# Generated by Django 2.0.7 on 2018-11-24 09:31

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(storage=utils.storage.ImageStorage(), upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('if_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='活动详情')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('content', models.CharField(max_length=200, verbose_name='评论')),
                ('floor', models.IntegerField(default=0, verbose_name='楼数')),
                ('is_add_info', models.BooleanField(default=False, verbose_name='是否回复')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('num', models.IntegerField(default=0, verbose_name='投诉数量')),
            ],
            options={
                'verbose_name': '图片评论',
                'verbose_name_plural': '图片评论',
            },
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片分类')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图片种类',
                'verbose_name_plural': '图片种类',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='大类名称')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('if_show', models.BooleanField(default=False, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '图片大类',
                'verbose_name_plural': '图片大类',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, storage=utils.storage.ImageStorage(), upload_to='images/%Y/%m', verbose_name='图片')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('if_active', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('pattern', models.CharField(default='jpeg', max_length=10, verbose_name='格式')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('cates', models.CharField(default='', max_length=200, verbose_name='种类字符串')),
                ('collection_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('download_nums', models.IntegerField(default=0, verbose_name='下载量')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名字')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='搜索词')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('num', models.IntegerField(default=1, verbose_name='搜索次数')),
            ],
        ),
        migrations.CreateModel(
            name='SmallGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='小类名称')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='images.Groups', verbose_name='所属大类')),
            ],
            options={
                'verbose_name': '图片小类',
                'verbose_name_plural': '图片小类',
            },
        ),
    ]
